# Release Drafter config
name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
categories:
  - title: '🚀 Features'
    labels:
      - feature
  - title: '🐛 Bug Fixes'
    labels:
      - bug
  - title: '🧹 Chores'
    labels:
      - chore
  - title: '🔬 Refactors'
    labels:
      - refactor
  - title: '📝 Documentation'
    labels:
      - docs
  - title: '🔎 Spikes'
    labels:
      - spike
